name: ci

on:
  push:
    paths:
      - 'src/**'
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: anilkponnam/python-app:v${{ github.run_number }}
    outputs:
      image_tag: ${{ github.run_number }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
          -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq 

      - name: update image tag in values.yaml
        run: |
          yaml_file="./charts/python-app/values.yaml"
          image_tag="${{ needs.ci.outputs.image_tag }}"
          yq eval -i ".image.tag = \"v$image_tag\"" "$yaml_file"

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update image tag to v${{ needs.ci.outputs.image_tag }}"
          branch: master
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0

      - name: Login to ArgoCD
        uses: clowdhaus/argo-cd-action@main
        with:
          command: login
          options: > 
            ${{ vars.ARGOCD_SERVER }}
            -- username: ${{ vars.ARGOCD_USERNAME }}
            -- password: ${{ secrets.ARGOCD_PASSWORD }}
            --insecure
            --grpc-web
      - name: Sync ArgoCD Application
        uses: clowdhaus/argo-cd-action@main
        with:
          command: app sync
          options: > 
            python-app sync --prune --timeout 300


        